name: pdf from mdfiles

on: push

defaults:
  run:
    shell: bash
    working-directory: ./docs

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}

      - name: create file list
        id: files_list
        run: |
          {
          echo 'FILELIST<<EOF'
          find . -name '*.md' -print 
          echo EOF
          } >> "$GITHUB_ENV"

      - name: Processing my found files from output
        run: |
          for i in $FILELIST; do
            echo "Do something with file ${i}"
          done  
      
      - uses: docker://pandoc/extra
        with:
          args: "az900.md -o az900.pdf --from markdown+table_captions --template /.pandoc/templates/eisvogel --listings"
      
      - uses: actions/upload-artifact@v3        
        with:
          name: az900
          path: az900.pdf
