name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker://pandoc/extra
        with:
          args: "docs/az900.md -o az900.pdf --from markdown+table_captions --template /.pandoc/templates/eisvogel --listings"
      
      - uses: actions/upload-artifact@v3        
        with:
          name: az900
          path: az900.pdf
