name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker://pandoc/extra
        with:
          args: "example.md -o example.pdf --template /.pandoc/templates/eisvogel --listings"
      
      - uses: actions/upload-artifact@v3        
        with:
          name: example
          path: output/doc/example.pdf
