name: pdf from mdfiles

on: push

defaults:
  run:
    shell: bash
    working-directory: ./docs

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}

      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "::set-output name=FILELIST::$(find . -name '*.md' -print)" 
          # > $GITHUB_OUTPUT

      - name: Processing my found files from output
        run: |
          IFS="," read -a myarray <<< ${{ steps.files_list.outputs.FILELIST }}
          for i in "${myarray[@]}"; do
            file_path=$(dirname "${i}")
            file_name=$(basename "${i}")
            cat file_name
          done
      
      - uses: docker://pandoc/extra
        with:
          args: "docs/az900.md -o az900.pdf --from markdown+table_captions --template /.pandoc/templates/eisvogel --listings"
      
      - uses: actions/upload-artifact@v3        
        with:
          name: az900
          path: az900.pdf
